---
apiVersion: v1
kind: Secret
metadata:
  name: tke-eni-webhook-certs-secret
  namespace: kube-system
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVHekNDQXdPZ0F3SUJBZ0lJVFdXQ0lRZjgvVkl3RFFZSktvWklodmNOQVFFTEJRQXdPVEVMTUFrR0ExVUUKQmhNQ1EwNHhFekFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR4RlRBVEJnTlZCQU1UREdOc2N5MW9ablF5TkhJNAplVEFlRncweE9ERXlNVFl4TkRJNE1EZGFGdzB6T0RFeU1UWXhOREk0TURkYU1ENHhDekFKQmdOVkJBWVRBa05PCk1STXdFUVlEVlFRS0V3cDBaVzVqWlc1MGVYVnVNUm93R0FZRFZRUURFeEZyZFdKbGNtNWxkR1Z6TFcxaGMzUmwKY2pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3h0WGlzNko3YWR5ak5uM3hHVQpVV0tTdml4LzFFRkxqZnlhRDFQc0hKdWp2QWg5ZE96MStpc2xkVDlXcjJHT0VmN1BFajJZVTZDNW1senJOQXFvCm5HNHdXOVJTblZDTHFmalYzLy9EdTl4bXhWMnVzM0NjSDdOcXA1eWtXYms4QUllUlFJUGZQdy9kUnpvVnNCSWsKOEk0dUFCQkJtMnl2bkhmMzdFdTVENjBDUXY3T1hEczA5bFVza1FwcHBxOVJtUytxQnZoYUIxUitvRzRwQWUvUApJVXdpV2hIREJmTHZ1c0hEYnltUGRIK2dya2hFSXE2RVFxaUxvUWhGWGN5MFVVZlZsK3JZOC95ZFBZaXhFQ2FCClBDZmd2ZU5ZaW9mTHpVbXlwS0VrRlNmTlV1VmdCdUVZdjNhMVhVRWF6UnpWRWtETlBRRnAxZTZneTlRVkxDcnUKKzFrQ0F3RUFBYU9DQVNBd2dnRWNNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRgpCUWNEQWdZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBRENCM0FZRFZSMFJCSUhVTUlIUmdoRnJkV0psCmNtNWxkR1Z6TFcxaGMzUmxjb0lrYTNWaVpYSnVaWFJsY3k1a1pXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHYKWTJGc2doWnJkV0psY201bGRHVnpMbVJsWm1GMWJIUXVjM1pqZ2hKcmRXSmxjbTVsZEdWekxtUmxabUYxYkhTQwpDbXQxWW1WeWJtVjBaWE9DSW1Oc2N5MW9ablF5TkhJNGVTNWpZM011ZEdWdVkyVnVkQzFqYkc5MVpDNWpiMjJDCk5IUnJaUzFsYm1rdGQyVmlhRzl2YXkxaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bGNpNXJkV0psTFhONWMzUmwKYlM1emRtT0hCSDhBQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEWUVVUGkzVjBxUzA5VlFFaWVxVVRRZApPRzdUNVZ4TUpxVWNhK3hGMWVWKzhtZzBxdWZWVyswTnZ2QnlpM0xZM1dqMkcyaGZSZUx6QzZIc1lBcTA3RXBpClJPRC9Yd2pQSnZ5SDF2dWFRTXNtaXdXT2hVY0taTEwwNzg1MHc1Skt0T2VyN0l4cE9IYXRvV21BNHUxUzNGdGQKbmRxTmNrRTVxZ0FhTGhYanNDWStZeHBSQ2ZQbVljbFFla3IyN2NzL1d1MlpncmorRnROWXRpUVc3emR6UUVvdwp1TFZ5NFgzSnhSK0lKNVpBckJseXgveUY3NGdqRE9MNU9ZWjBjMHY2NGZ0R1JBV0NhZ3VkVGFKNmRaOStBVEcwCjA5YXRhOGtYanh1REtFM1cvZEEzdmF6SzVLblRlRlpLYm0xTk9WaHRPNGJ3WkF2bENUdEpEV1BSa2I3Z2QyQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBckcxZUt6b250cDNLTTJmZkVaUlJZcEsrTEgvVVFVdU4vSm9QVSt3Y202TzhDSDEwCjdQWDZLeVYxUDFhdllZNFIvczhTUFpoVG9MbWFYT3MwQ3FpY2JqQmIxRktkVUl1cCtOWGYvOE83M0diRlhhNnoKY0p3ZnMycW5uS1JadVR3QWg1RkFnOTgvRDkxSE9oV3dFaVR3amk0QUVFR2JiSytjZC9mc1M3a1ByUUpDL3M1YwpPelQyVlN5UkNtbW1yMUdaTDZvRytGb0hWSDZnYmlrQjc4OGhUQ0phRWNNRjh1KzZ3Y052S1k5MGY2Q3VTRVFpCnJvUkNxSXVoQ0VWZHpMUlJSOVdYNnRqei9KMDlpTEVRSm9FOEorQzk0MWlLaDh2TlNiS2tvU1FWSjgxUzVXQUcKNFJpL2RyVmRRUnJOSE5VU1FNMDlBV25WN3FETDFCVXNLdTc3V1FJREFRQUJBb0lCQUZiOXRveklnbEMzdXRQRQppOTRxbmdURlUvelBZUjZ3SjZwUmIzby9uUTlJeEF6a2ZxRXVXRkI4VFhMdklQeHUyTlZkVXk2UU0yRGJRdTJ1CkhFdGtWY2VoempLSW02V1BVT21odmFrajd4dDdIZ2Z0bzhva2VqbmlqVDJTRFZKTzIxV0tDcXA5Ynl0cDBBMlYKODRhejdFbFBHK2tYc0hwYy91dm53T2RUTG4xeDJtQVZseDByQkU3ZERveVdGdWRZN0ZTMmhIUDd1MUFkM2t0UwpBaWZFb1I3SjFRL1g4alZCblhlWDZBekJUck1xcG95ZE90RTYyNnBabkQwcFNDdjJoS3FHRVczaHpobVhoTkZiCmE1NHdQMlpxeENzdjM4aTZVdUhMemJIVEh3M1FibWlRZkxYd05Jc3VGNzRxekRWdVNsMllZaUtONG93dXNiNUMKM0psMXhhRUNnWUVBM1lGVzNIc2cwLzFMbnp5R0Z4OVEyMzhOSGs2bVB3OC90UmVGUkNxTWNGWXo0RWt5UmE5bAoxUkUzMld2bVl0YnZwcGlqQ0NNQlFQWjZWcEdCZHcxQnhvSUkrUkpldHBaOHl0YTg3TjROeWV0Z2FMcFFEZndGCjV1eEVYZ2hQY3FCU2kvbHdWOXZnWDNUQU1WaGwrZDJLL0V2cm1iUG1wbUN1aDBtRDdYUkxRL3NDZ1lFQXgwZDAKZUZ1b0dUazFKRVhreGNmQUs2Y05VbUE5UzYyckZHVlJNYldaVnMrUlNaU3V0dDdiRklIY3lxbno3YU1MWTAwOQpFd0FLTDA0dHU0UEt2RWNyVGordFQxaHI1cGdSdC9BVC82ZWZvT05LVFBBajl3OUJvUVdNSXBEbFdoMFI0UTJFClBQQXZNRW1LWFE2SVJZYVFSQkozdU1YOGpMSnJjSHNMN1VwSmlic0NnWUVBcXRNS2wvTGxPRmZKc0Q1Tzh4b1YKazVHQ0huTnRSb2lPQ3l6ZWU5bU1nVDRadDhqN1dqNlFmQ2RST1A0N3FOSTE4L2NYRkRsYXlDek40R0ZLeFBPVwpYRzhBV0lYUVFXUUJUYlVaOGxxMXE1azR1c3VrM1lRVlVTZTQrZ1BTc1lYdTQwQTFZYXlTZDB0a3hTbDFTNk9OCmdsRlNtekRnbWtOSmxkQWVURXc1bDIwQ2dZQXQxR0VVelA5N3pZeExLMGZSdEg2ZGkyMms1RDAwaWx3dDlKOFgKcjR2MFN3Zyt3OUxxZTVZbXdUYmw1UEFVVnNybnEzdkFRdUlVdndZRmVlbkdJeGZ5aHZKMHJRRWpweFZzRitxQgpnU3RVOVBEQmdQakVlTjIvQ21lUUM0S3pscnZsNWhYamJkbHNZWDFRcVdidGxtVFhRdWdGdG9LK1dNb2N0QytxCkFzdW13UUtCZ1FDUmxKYzAxdGpzYlIxTmZlQytyb3FkbkNsMDF5TndqdDVuaUZ5aWU2a2hmMksxcmZEUTVYdzgKcnNiTFgveDVrT0RueE9CMmVCWWRwRk1LeFBJNCttNUVrVCtVZSszMGZqVTJwTGs3TnltdFUzeFZkTHFGTW1yRQo0dklDVXc3WU91d0NMejV4R3dYK3Vabi9wK1ZFcjlWY3JhdFY0eWllTERCcEJXYXp3cEx3M2c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tke-eni-webhook-admission-controller
  namespace: kube-system
  labels:
    k8s-app: tke-eni-webhook-admission-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tke-eni-webhook-admission-controller
  template:
    metadata:
      labels:
        k8s-app: tke-eni-webhook-admission-controller
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/tke-cni/tke-eni-webhook-admission-controller:v0.0.1
        args: ["--tls-cert-file=/webhook.local.config/certificates/tls.crt", "--tls-private-key-file=/webhook.local.config/certificates/tls.key", "--alsologtostderr", "-v=4", "2>&1"]
        imagePullPolicy: Always
        name: tke-eni-webhook-admission-controller
        volumeMounts:
        - mountPath: /webhook.local.config/certificates
          name: webhook-certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: tke-eni-webhook-certs-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tke-eni-webhook-admission-controller
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    k8s-app: tke-eni-webhook-admission-controller
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP