---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: tke-eni-validating-webhook-config
webhooks:
- name: deny-invalid-statefulset.tke.cloud.tencent.com
  rules:
  - apiGroups:
    - "apps"
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - statefulsets
  clientConfig:
    service:
      namespace: kube-system
      name: tke-eni-webhook-admission-controller
      path: /statefulsets
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lJYWRoSDRXNGRYcTR3RFFZSktvWklodmNOQVFFTEJRQXdPVEVMTUFrR0ExVUUKQmhNQ1EwNHhFekFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR4RlRBVEJnTlZCQU1UREdOc2N5MW9ablF5TkhJNAplVEFlRncweE9ERXhNVE13TlRBeU5UQmFGdzB6T0RFeE1UTXdOVEF5TlRCYU1Ea3hDekFKQmdOVkJBWVRBa05PCk1STXdFUVlEVlFRS0V3cDBaVzVqWlc1MGVYVnVNUlV3RXdZRFZRUURFd3hqYkhNdGFHWjBNalJ5T0hrd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDWGMzVEppcWZlT2MrMnVyT3d2ZXc5U29xQwpEQmRaNjZydzdMckJPbDVUbHdYSVE1bDJGUitFSGFhT1VXZDB3MGt2dmVVN292Y1NKYk1Fa1JxU0JuSWFYSk96CjZHaDBEL2J2VzIyOG5kSks2emw3SDE2VWdublpOQ09NckxZZGVOVFlNSVRSYmpsZDllcURKR3A5OFhvNU40WTYKTXRvVW9xQmlPNkJwM1BraHlNWnJqSytJaTYxNFJPQkhCVTh2ZEJJdDA3bTU4b3VCcmk2NTNDRTljSzBjWkovNApCaVFSZm9rRkVrWTZXcnpKRmRwL1BsZ05lY3lYa1llWUJQVFI1VzFNM3N3Z25lMUhMT2RsK2xoNEFVcXdxVFFnCkxNNU1hZXlpcnliQzRJc1piVHhVN3M5VDNUaGthT29ZS05tWndRVFdlNW83UlNMdzNzbWpiejRCTmc1ZEFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQgpCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUxoN3pFcTRBClJpdHNPSGY2MHdhTXQ1V2d1UFEzTGxSYmEwQ1dQVmhiS3BnUlI5U051WWR5aFdGd0thTW1xYXlzRVVnMWc2OGwKUU01Z0J3LzVCbm5lc0pTb3hmMWR3eWh1dWU0M24rRzlkV0hQMFZWa3M4bms5V05jdENSMlRpVk4wZW5ZOFNJWgpLUzBWTWJ1akQxRUJMdHU1RFE0Szd0Q1p3UTFuaE95MVdoQ1JEY0VjMjhORlhnN0VtcVBMeklPRWkrd1pZR1UxCm96WCs1THpBbGFiOHlSYjY2NDZ1QmdwbHdqM3Z0dWhmd3p0K1JpWEdLS2w3TUc3NklieFg4ZVNidnJIUllveTgKaUdrendJUER0WTl5NmRRd1UxZzFGYWlRN0tsdjdUR1JTeTFUU240UDNsb2NEQ2hYZVl4d2RBMkRpL3EwcWRZQgpkcVNoZnFzNXQvRC9RUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tke-eni-mutating-webhook-config
webhooks:
- name: add-pod-underlay-ip-request.tke.cloud.tencent.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    service:
      namespace: kube-system
      name: tke-eni-webhook-admission-controller
      path: /mutating-pods
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lJYWRoSDRXNGRYcTR3RFFZSktvWklodmNOQVFFTEJRQXdPVEVMTUFrR0ExVUUKQmhNQ1EwNHhFekFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR4RlRBVEJnTlZCQU1UREdOc2N5MW9ablF5TkhJNAplVEFlRncweE9ERXhNVE13TlRBeU5UQmFGdzB6T0RFeE1UTXdOVEF5TlRCYU1Ea3hDekFKQmdOVkJBWVRBa05PCk1STXdFUVlEVlFRS0V3cDBaVzVqWlc1MGVYVnVNUlV3RXdZRFZRUURFd3hqYkhNdGFHWjBNalJ5T0hrd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDWGMzVEppcWZlT2MrMnVyT3d2ZXc5U29xQwpEQmRaNjZydzdMckJPbDVUbHdYSVE1bDJGUitFSGFhT1VXZDB3MGt2dmVVN292Y1NKYk1Fa1JxU0JuSWFYSk96CjZHaDBEL2J2VzIyOG5kSks2emw3SDE2VWdublpOQ09NckxZZGVOVFlNSVRSYmpsZDllcURKR3A5OFhvNU40WTYKTXRvVW9xQmlPNkJwM1BraHlNWnJqSytJaTYxNFJPQkhCVTh2ZEJJdDA3bTU4b3VCcmk2NTNDRTljSzBjWkovNApCaVFSZm9rRkVrWTZXcnpKRmRwL1BsZ05lY3lYa1llWUJQVFI1VzFNM3N3Z25lMUhMT2RsK2xoNEFVcXdxVFFnCkxNNU1hZXlpcnliQzRJc1piVHhVN3M5VDNUaGthT29ZS05tWndRVFdlNW83UlNMdzNzbWpiejRCTmc1ZEFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQgpCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUxoN3pFcTRBClJpdHNPSGY2MHdhTXQ1V2d1UFEzTGxSYmEwQ1dQVmhiS3BnUlI5U051WWR5aFdGd0thTW1xYXlzRVVnMWc2OGwKUU01Z0J3LzVCbm5lc0pTb3hmMWR3eWh1dWU0M24rRzlkV0hQMFZWa3M4bms5V05jdENSMlRpVk4wZW5ZOFNJWgpLUzBWTWJ1akQxRUJMdHU1RFE0Szd0Q1p3UTFuaE95MVdoQ1JEY0VjMjhORlhnN0VtcVBMeklPRWkrd1pZR1UxCm96WCs1THpBbGFiOHlSYjY2NDZ1QmdwbHdqM3Z0dWhmd3p0K1JpWEdLS2w3TUc3NklieFg4ZVNidnJIUllveTgKaUdrendJUER0WTl5NmRRd1UxZzFGYWlRN0tsdjdUR1JTeTFUU240UDNsb2NEQ2hYZVl4d2RBMkRpL3EwcWRZQgpkcVNoZnFzNXQvRC9RUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K