kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: tke-eni-ip-webhook
  labels:
    k8s-app: add-pod-eni-ip-limit-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: add-pod-eni-ip-limit-webhook
  template:
    metadata:
      labels:
        k8s-app: add-pod-eni-ip-limit-webhook
    spec:
      serviceAccountName: add-pod-eni-ip-limit-webhook
      containers:
        - image: ccr.ccs.tencentyun.com/tkeimages/add-pod-eni-ip-limit-webhook:v0.0.3
          args: ["--alsologtostderr", "-v=4", "2>&1"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          name: add-pod-eni-ip-limit-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: tke-eni-ip-webhook
spec:
  type: ClusterIP
  selector:
    k8s-app: add-pod-eni-ip-limit-webhook
  ports:
    - port: 61679
      targetPort: 61679
      protocol: TCP