---
apiVersion: v1
kind: Secret
metadata:
  name: eni-ip-webhook-certs
  namespace: tke-eni-ip-webhook
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVxakNDQTVLZ0F3SUJBZ0lVY1lzUW9ud2RlZGdhTXBoOTJIY3RpblRhZHp3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU1TVRJeE1UQTRNRE13TUZvWERUSXdNVEl4TURBNE1ETXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc1QyWUFHM3cvSnlXaFpRM3c5UkwKbUtEb0hsclQ1SnliZXNjVlFOcERnSCtnUWNjVFduRHgxNHFOK1Zab1VPcXhpRVhKaXE1WjE2VXVxclc5MXRxeQpsNTRieHAxRHAwRlhBWEZGZG13NmZzWG4yRGdXNStwYWlOblNIaGZHRHZFemE3d2pNelJianlLSlZNYUNUaGdOCmJIMnIrSFlNUTlIQjNzL21iQXByTUdFUVVRSHg2QW93OUtqWEFtQ0t4bWlHdUEvamlOMkdxd2VjRldYWTBKK1QKbTZWR0FENUg4ZlZTYmhsRlhWMGI4K1BDL09welJnSzhsUEdabjc4UzNMeWNCVUtPRDUzSjdjNW5YRkl6SDg5UQp6ZGIxWUloRldPY1pjaWJQd25ibzN6aTNraXdxdjRkMy9TU0orMXBBdFVmbHhQNlh1RGxndU9MOWFFcEdkaGtTCmV3SURBUUFCbzRJQlVEQ0NBVXd3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUYKQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkVRTTJXSVhlc05raEcvYVVLRnNISUNYQ200UwpNSUgzQmdOVkhSRUVnZTh3Z2V5Q0wyRmtaQzF3YjJRdFpXNXBMV2x3TFd4cGJXbDBMWGRsWW1odmIyc3VkR3RsCkxXVnVhUzFwY0MxM1pXSm9iMjlyZ2pOaFpHUXRjRzlrTFdWdWFTMXBjQzFzYVcxcGRDMTNaV0pvYjI5ckxuUnIKWlMxbGJta3RhWEF0ZDJWaWFHOXZheTV6ZG1PQ08yRmtaQzF3YjJRdFpXNXBMV2x3TFd4cGJXbDBMWGRsWW1odgpiMnN1ZEd0bExXVnVhUzFwY0MxM1pXSm9iMjlyTG5OMll5NWpiSFZ6ZEdWeWdrRmhaR1F0Y0c5a0xXVnVhUzFwCmNDMXNhVzFwZEMxM1pXSm9iMjlyTG5SclpTMWxibWt0YVhBdGQyVmlhRzl2YXk1emRtTXVZMngxYzNSbGNpNXMKYjJOaGJJY0Vmd0FBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUlpRWdySWJZK0Irc1lnTTh0M0pZa1NLTwpVdVN6ZTRadTZFeUdhQ1ZnUmk5NDByRUk3MUNuOHBac1FORXpvZWFaWjU1MFZoOWdid0l3Y0ZCT0xIZVNLdExHCmpYUHE5bFhmZjR0OWs5Ukh4bFVOcDhjYUpPenlTRXRXTGtUL3AxaXRoK1F0Tk1sTnZjZ0ZPa3haQVA0UHROTTMKUjBNT2xjNWVkNVZFaDYzUjMwQmg5RDlXQlNoeXBJNXg5cWRoNU1vcGdTU0lGSWRCZU56MHArRXR3c3YzeGZuQwpWUlcyVTQwT014OHZlNGpmSlh2Z0VVRTFmeWUxS2NEQVAwSVBwZm82eWM0VEZpT1k2Q01LeHc1Tm1jYmh1NDg1CjZtWDNlUjAzMnBjaWNyWW9LZHcvODFYRnc5SnNEWXkrc01INmdqVnVPMUhpNS9RQkxaUU9ucFJlT2g0VFlBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBc1QyWUFHM3cvSnlXaFpRM3c5UkxtS0RvSGxyVDVKeWJlc2NWUU5wRGdIK2dRY2NUClduRHgxNHFOK1Zab1VPcXhpRVhKaXE1WjE2VXVxclc5MXRxeWw1NGJ4cDFEcDBGWEFYRkZkbXc2ZnNYbjJEZ1cKNStwYWlOblNIaGZHRHZFemE3d2pNelJianlLSlZNYUNUaGdOYkgycitIWU1ROUhCM3MvbWJBcHJNR0VRVVFIeAo2QW93OUtqWEFtQ0t4bWlHdUEvamlOMkdxd2VjRldYWTBKK1RtNlZHQUQ1SDhmVlNiaGxGWFYwYjgrUEMvT3B6ClJnSzhsUEdabjc4UzNMeWNCVUtPRDUzSjdjNW5YRkl6SDg5UXpkYjFZSWhGV09jWmNpYlB3bmJvM3ppM2tpd3EKdjRkMy9TU0orMXBBdFVmbHhQNlh1RGxndU9MOWFFcEdkaGtTZXdJREFRQUJBb0lCQVFDUXBrSWRaNXliclhnegpBR29haW5JLzJHSllFNnlIRVVEYkRRdE5hRlJhMU00SG9OOHNtcXpsU2hEZ2d5S1RsMWJZYm93emdHT1dXUnNpCit6dzUwemFhQXRHTVlPREw2Y21HUmRsNDhvOHkwM1dKd3d6K3JRYkNWWExrV0dhdDN6QW1KdDliZE1tY29ZVVAKQ1F0ampNRzMzMEN3Z0RjMlNrUTlBZE4rTFdxWmllRm9PNnhWV2J6MXVKUURxWCs4Tll4Wlp1dzdqY2ZON1RHLwovcGhBdnk1ZUJmUnU5SFF6S2lrSGh6NGRtMXhFcXAzVksyUDBNUStMVElnYlVLY2ZVbTQzeU93L1ZaYnk1L1dQCmUya3N0eElaNTMrS1FzZkJBdEs0SHloU3pyN21oWXloTDBaSFNaOXRFdDV3VldybXUzaTBwTlBMdE5RVDZiOTcKRlcrZTRWblJBb0dCQU1hS2tQRm1xMHQyRzB6L0Jtb1VTR3Jla1creXYrSVVqS0Z1ZGIwQVpHa2k1ZzlKNVQ0ZQovdzdraVJ4Z0hjRi92NE9yMFBUdjVTTkloYlVSak1BL1VyRHVUaDVwdGtzazRXTzRaT0tNbndzSjFYcXV0dDB6ClNrNXZqNW9mRHFCZWdTbXlrdytwbmxsMno2MmhuSFJSR05tcU9rR1NUTEJnSCt3ZXM1YWk3Z1ExQW9HQkFPU0kKNmNSazVGRmUzRGV5ZWJyUTU1NURHak5PSXhCbng4eitvL0tuaFlWQW53bThZa1U1VDNyQTY0K2M3alQrK0FBWgpzblZQdWRDNDNuckozbGNZVVllUDlPTEpPbHEwRUJPUDcwMTk4aCtRK2VhRERlZlR4Z2gyTUtDZk1MYzJvZXlYClBUL3RoamluazJHNFJZRFRGSjY2UFRVbUdudzE5MmRoSWdESFlUSHZBb0dBQitwOGJ2T04vdHM5cVdzOW9Uc2YKekFzRnQzTmtEU3FPbE4wbm1wcUtabHE2MjM4eHdiRlFzQkpTbVN3SDQ3QXBQYUc3R2hqNmhOYWVaaUxGL3VCSApkc0I1b3VMS0h1TGdqYTVMYjNEMTRtWEkralEvSEVDd1JNSlQ4bXdzbEI1UWZnNGRxUEUxWEJITm8vbWVtRkNuCmNmNUVobHJEN2dCWEpYM3Y0U0NyNXNVQ2dZRUFtWUoyTkZ2cEdkZDBhVjFUYzIrY0JhemhUcEV2OEhjbHVNZGIKYlVXbDVLcFJxZ0tHcUNVbEJEbk9nWHRTYnZyTnI1T1RVa1dwZFZDWThUWGtTZkNsNHorSnFVU3VFL3RieVNnbwpBSStYTWlqNkZDTDRGajhraU02TFAzbHZDY0tDNWg5NUh4WDMwTnFQbjFaZUtYaWdJemJLb29iang0ZWdsaXFpCjRvOEs5TFVDZ1lCaENUZzFwVytSYVVrUXZBNXhaYVpiWDkzZ0RrZ1NXektHTEtaZnh1WGhZamdWU1FqL2REOXQKN3FKb3lRS2JjM0FWQ1JMWTJ4ei9xZHlMcjlVbWxEeWhkN2c0UVhRT1dnZ3VUTzFrdHhQRGIxcU9naHhoNTB3MwpiYUJKNUZpTllZeHBhY2QwMXlaTC9XbUhLcHBNVHZQRkpJL21ZRlhsd0JKWHhoY0NnWHVoVUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: tke-eni-ip-webhook
  labels:
    k8s-app: add-pod-eni-ip-limit-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: add-pod-eni-ip-limit-webhook
  template:
    metadata:
      labels:
        k8s-app: add-pod-eni-ip-limit-webhook
    spec:
      serviceAccountName: add-pod-eni-ip-limit-webhook
      containers:
      - image: ccr.ccs.tencentyun.com/tkeimages/add-pod-eni-ip-limit-webhook:v0.0.2
        args: ["--tls-cert-file=/webhook.local.config/certificates/tls.crt", "--tls-private-key-file=/webhook.local.config/certificates/tls.key", "--alsologtostderr", "-v=4", "2>&1"]
        imagePullPolicy: Always
        name: add-pod-eni-ip-limit-webhook
        volumeMounts:
        - mountPath: /webhook.local.config/certificates
          name: webhook-certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: eni-ip-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: tke-eni-ip-webhook
spec:
  type: ClusterIP
  selector:
    k8s-app: add-pod-eni-ip-limit-webhook
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP