---
apiVersion: v1
kind: Secret
metadata:
  name: eni-ip-webhook-certs
  namespace: kube-system
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVqakNDQTNhZ0F3SUJBZ0lVVklzSk1xdnd1WUh3N0MxQldFdUZCNzRJNnc0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU1TURneU56QTJOREl3TUZvWERUSXdNRGd5TmpBMk5ESXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdkZ5a1BKMUVkQldteWFjaUduME0KektBVUI0V2F3a1ZPRmtJbjUveDFNQzJlS1FUenI1dlMxcm9GSDFCZjdRZVZHWUZZL0R6VGVYalZqVVRYcFB2VgpueVM1ZHUvajJKdlBSVUJvdXBRT0UyWjVMd3gyTURzWFZQcEkyaFFWMmJYNWUzNG1GRHFIYnV3SkVCOEw1TDByCmllNCtwODU5dERNNi96anMvR3FLdG05ZU0vQUZzWW5rZlJzNVNNaHkxc1dwY0doWll2M3hBbEtNWm01WTNHbGoKcjlkWHR1QmhURHEvR1NDZzB3dDU4MmVKSERodnJ4NE9SNTRJUW5lUXdxVktCcG5iU2tlZGZPbnJobVkvanZtbgpBbUczUTA3VmpFbllzNmlCcmQxbFBZMUZXd0xqS1NlMGpWTEw1azBIK0xYTCtjdWVCek12WVA2YUtOdUN1bjVhCkJRSURBUUFCbzRJQk5EQ0NBVEF3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUYKQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkJUVDlRaDc5ZU1FV1hjem56dkZyWFVaT1NIaApNSUhiQmdOVkhSRUVnZE13Z2RDQ0tHRmtaQzF3YjJRdFpXNXBMV2x3TFd4cGJXbDBMWGRsWW1odmIyc3VhM1ZpClpTMXplWE4wWlcyQ0xHRmtaQzF3YjJRdFpXNXBMV2x3TFd4cGJXbDBMWGRsWW1odmIyc3VhM1ZpWlMxemVYTjAKWlcwdWMzWmpnalJoWkdRdGNHOWtMV1Z1YVMxcGNDMXNhVzFwZEMxM1pXSm9iMjlyTG10MVltVXRjM2x6ZEdWdApMbk4yWXk1amJIVnpkR1Z5Z2pwaFpHUXRjRzlrTFdWdWFTMXBjQzFzYVcxcGRDMTNaV0pvYjI5ckxtdDFZbVV0CmMzbHpkR1Z0TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzaHdSL0FBQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFCVFhkS3lvWmh6ZzNIY2xGbkZRc0xmS2h6UytDSEdvRE9tQW9EQzJQYVBFY1phL0RycWVkd1BSam9weDJ4OApLRFVWTTdockZsWlJYekVOUzhtZ1J4b25yZ2w2dmtPRXIzbVdObVFhd3lVclpiNzhWRlZENHllSEl3SUZjbVdrClVsYllkTDNqeWFrSEJGc1hEYXBZR3JZYTBUK3NRak1GRGJyV2FPbGo3NU1RR0prV1ZxSXFYdlhLb1ZOQzdWSTYKcTV5NGRVcGhUbjczZFlXNU1wc1JObW9tMi9GK0I3aERaTEs2TzdhdnYvcXg1T0pkYVFyL3FKWjNPUFJKcysyMwprVzBNL2NxbGhIUUZxdHBMcjJBbnQxZGVDWDVZSWdnSDBKc3JyWkkvTlRHdTlFVzNQaEpCMXNRYk1jNkw5RGIvCjhNQmMvN2p4R0ZxQmtrV0xaYnJSVWlKdwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdkZ5a1BKMUVkQldteWFjaUduME16S0FVQjRXYXdrVk9Ga0luNS94MU1DMmVLUVR6CnI1dlMxcm9GSDFCZjdRZVZHWUZZL0R6VGVYalZqVVRYcFB2Vm55UzVkdS9qMkp2UFJVQm91cFFPRTJaNUx3eDIKTURzWFZQcEkyaFFWMmJYNWUzNG1GRHFIYnV3SkVCOEw1TDByaWU0K3A4NTl0RE02L3pqcy9HcUt0bTllTS9BRgpzWW5rZlJzNVNNaHkxc1dwY0doWll2M3hBbEtNWm01WTNHbGpyOWRYdHVCaFREcS9HU0NnMHd0NTgyZUpIRGh2CnJ4NE9SNTRJUW5lUXdxVktCcG5iU2tlZGZPbnJobVkvanZtbkFtRzNRMDdWakVuWXM2aUJyZDFsUFkxRld3TGoKS1NlMGpWTEw1azBIK0xYTCtjdWVCek12WVA2YUtOdUN1bjVhQlFJREFRQUJBb0lCQUdBWXQyV0JLbm82elpPVgpZKzIxbklFTXJndEVXemIvbXAzNmRGZURVZG9aZTlZYmc2TTAwVFRoUkZtOGJLUUZ1VWlBMkFBZm5CZ2QwSDA1CkFQZFh6NTFZWkJKTXdxWXduMmNLUENQc0F0NWM2amhabURaMC95dElZVUI0L01qTWNSSlN3bVNSazZUQVlNTkwKdzRxWUJBMWpjYTIweUNiVitDUmJTM1JmZXBNbGowK3lsbFMyMENsZTVOSko0cTVTME9HcHVVR1plYzhpRmR3SQpUZDFQUVNDT005YnZ2T1lDRzRraEJzc1M3UDBiYk1QOWtJTnl1LzJZa0ppWUd5OVBGN3JVWC8zRk5MditkajZDCmpOVEJ2Q1BVck5FbzFFZXMrMUVWWjdhVTZsVldqSHZEOXV0bnNLaVE1eHB1OVFOcGhsWkluakVySVZkSVZ3WUQKcEk5SzBzRUNnWUVBN2taZWN2aVlwT1F0MnVCQ20vM2ZVd2gxNkxSS3huOGc3VkdldFhTN2JTbTFMQXNlT3J5NQpkVVBuUkduc2lxblFvRi85VlJrWmgxYjVmVDBUSHl2VGZUREE2NmdPakdtZXFNRDZteWx1YTQ0amJaZktlb1hMCnZOeUdUQ1RnZE9Od1V5M1hxY1liMzdZaEo2QTFRREpIL1RtOHRJdFhpeVVUOCt6aG4weDZ4RkVDZ1lFQXlsKysKenZLQytIOFFDVjlHbkdNZEhvZ2xjUlA5NEdKQmVJR1dlM0txZWRKVWROZ3RoMW1sNjlwNDQ0YldvK0p4a1pHZQpmYTJnL3JmVGYvTEdEMXZjZVNRZ3ozV1hQMHdKTUpZNzhFdHVMUklRUkRCb2t1byt4OXFtY09PNDN6Ym9vU2JCCnZhN3JQb1g1dmpnMzlUVHkwaURXcjRaT2pIRVNUUUJCdjlHMVVYVUNnWUVBMzMwRlRkVTZaejdXZTd0by9xTksKZXJrdXpzdDhiMTRDWmxYdUJNaXVtNTlKSFR4NGFDTm4yRU9PZ2E3UWZPYjJsZFl5NlVTWG0wZkt6dHNnT2xhRApFYU5POERvN0d4eGVBbTZ2SUNYbU9kK2gvME1tV1hGeFBYMmlRWDA5UXFXcFQzdHFFd1dNVTNLaSttWGNUSkJjCjBYajhOR09XQXg4TjdmYTdVUTBOQVdFQ2dZQmVYdEdhcllvWG1TRUFUZGFlbkxWNmhHQjVYNm8yMVhyVVdCRzEKVlY1YjJwSVp2cWxVZ2FDVzRGVVpQTXFndDdyZjkvamhnSE1mOU5jQ3hsSkgzVDF0bkVSVW1mQkN5eEZKLy9USgpkRk5YWHlJSXVrNDVuRlJVWEFqYmdjVzNDV0xucXl3VGFSczRGNy9EVFhJQ3ZZTXlLN0FSUDk4bkxKOHRHeDZOCjladkk5UUtCZ1FDRDZjbGxDSDQvcnNmTEJHNURXd1Bsc1hkdjJsdjU3YUEyaXlJY1VEUUxnM1hUaGZlUE9IbEUKVE1iZEt2YzNabXJLSWxISVoxenlPSEZtYzhhMk9BZ21HZU9WSlMxYmlPelhHcU40ekpDcHhIdEJRei9SS25GbAprK2x2bk4xRHpoS3p6TXpPZEs0cUF1VnkxblhvcGxxcEo1SjBNTTRYVmpHYXRGbmlndUVHMEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: kube-system
  labels:
    k8s-app: add-pod-eni-ip-limit-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: add-pod-eni-ip-limit-webhook
  template:
    metadata:
      labels:
        k8s-app: add-pod-eni-ip-limit-webhook
    spec:
      serviceAccountName: add-pod-eni-ip-limit-webhook
      containers:
      - image: ccr.ccs.tencentyun.com/tkeimages/add-pod-eni-ip-limit-webhook:v0.0.2
        args: ["--tls-cert-file=/webhook.local.config/certificates/tls.crt", "--tls-private-key-file=/webhook.local.config/certificates/tls.key", "--alsologtostderr", "-v=4", "2>&1"]
        imagePullPolicy: Always
        name: add-pod-eni-ip-limit-webhook
        volumeMounts:
        - mountPath: /webhook.local.config/certificates
          name: webhook-certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: eni-ip-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    k8s-app: add-pod-eni-ip-limit-webhook
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP