---
apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: add-pod-eni-ip-limit-webhook
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: add-pod-eni-ip-limit-webhook
  namespace: tke-eni-ip-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: add-pod-eni-ip-limit-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: add-pod-eni-ip-limit-webhook
subjects:
  - kind: ServiceAccount
    name: add-pod-eni-ip-limit-webhook
    namespace: tke-eni-ip-webhook